---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: gitea-config-mailer-passwd
  namespace: gitea
  creationTimestamp:
spec:
  template:
    metadata:
      name: gitea-config-mailer-passwd
      namespace: gitea
      creationTimestamp:
    type: Opaque
  encryptedData:
    password: AgAMkOZIZgh2GS+DNw4bxleetcjoKQIOFEDmrMslE4ynZOKV1W2ntwxTAKxbF6H5mXS2tNZGMfZsPSujsFTnACYTQZdTAjmvM+F2dkc6xKTHMrrwz/ouEV8u+Rmv4LxUzmRzDq0xK478xt3/zSMkpe4ARMeelqJ2qBmY9Hg4CO5EQ6G8ZlZurV69gdY2Uof/udndNuqKGCDuhbIOAVrNgU6kwOxlT5cq308HVjsIHsdtFKwMC6fr2p6nRU4dwDPmZzoRDticVDHHmqO9c5XOC1jP9QmvniBpstJxY/ESllh8qhrZigNggszTubfRAy6ESfC0RSufFQIWbO0WIzFI3WZxCM+3b+OM+ADQDsbGVVBfax2yUIP94ybPaXog1+3pCbNynnxDuHz7eRrS8s+5xsOkIPvZneHpjQJdZMQaTqeGdwBAqiOTdjk4BpRauOD0gDxZbm/2VApW9RDythB9oyYf5lHoz2Vvb15jfPnN1fc7KXhtonyefjlDMwsA/UKzrLAWuahuqpczNQ2pdzyhWnhx+Oq/KDlYDbT3cuCLsSOl4uNNA8tyfuX7ZVy35Ws+Mz9ZslH6LViur44b5I2IV2/uBXJ6d+HvnJomyy07jh4oaNVO0G22IQ6oVFdGBuKJ5ddA/0gHpFmNcPCZaqw+m2HZMrEbpmBcEoNbIx/t5WT8/9r8yN0gXI3ATYiJ6ZIeNbi3L/o/IgTg48EVfhS6